### ISSUE TITLE
Add 'since' and 'forRemoval' arguments to the @Deprecated annotation.

### ISSUE THREAD

**Issue by qureshiwaqas** [OmniaAlam/OpenTracks-Winter-SOEN-6431_2024#11]
Add 'since' and/or 'forRemoval' arguments to the @Deprecated annotation for getTrackPointCreator
Deprecated annotations should include explanations [java:S6355]

public class TrackRecordingService extends Service implements TrackPointCreator.Callback, SharedPreferences.OnSharedPreferenceChangeListener, TrackRecordingManager.IdleObserver {

    private static final String TAG = TrackRecordingService.class.getSimpleName();

    private static final Duration RECORDING_DATA_UPDATE_INTERVAL = Duration.ofSeconds(1);

    private RecordingStatus recordingStatus;
    private MutableLiveData<RecordingStatus> recordingStatusObservable;
    private MutableLiveData<GpsStatusValue> gpsStatusObservable;
    private MutableLiveData<RecordingData> recordingDataObservable;

    private Handler handler;

    private WakeLock wakeLock;

    private TrackPointCreator trackPointCreator;
    private TrackRecordingManager trackRecordingManager;

    @Override
    public void onCreate() {
        super.onCreate();
        Log.d(TAG, "Create");
        handler = new Handler(Looper.getMainLooper());
        recordingStatusObservable = new MutableLiveData<>();
        updateRecordingStatus(STATUS_DEFAULT);
        gpsStatusObservable = new MutableLiveData<>(STATUS_GPS_DEFAULT);
        recordingDataObservable = new MutableLiveData<>(NOT_RECORDING);
        trackPointCreator = new TrackPointCreator(this);
        trackRecordingManager = new TrackRecordingManager(this, trackPointCreator, this, handler);
    }

    @Override
    public void onDestroy() {
        Log.d(TAG, "Destroying");
        if (isRecording()) {
            endCurrentTrack();
        }
        if (isSensorStarted()) {
            stopSensors();
        }
        // ... (other cleanup code)
        super.onDestroy();
    }

    // ... (other methods)

    @Deprecated
    @VisibleForTesting
    public TrackPointCreator getTrackPointCreator() {
        return trackPointCreator;
    }
}

![image](https://github.com/OmniaAlam/OpenTracks-Winter-SOEN-6431_2024/assets/64982453/3f802223-87bb-464a-9e1c-e22b68f47597)

**Comment by qureshiwaqas** [comment]
This issue has been addressed and fixed in the latest code changes. The relevant commit can be found in commit aa15cd4

**Comment by OmniaAlam** [comment]
@qureshiwaqas Re-opened and reverted the old merge
